stages:
  - genLicense
  - checkLicense
  - build_sample
  - build_module
  - build_master
  - build_feature
  - clean_build
  - plainPW_check
  - oss
  - cov
  - fossid
  - release_customize_sdk

genLicense:
  variables:
    CODE_COMPILE_ARCH: 'TC32'
    COV_PF_CATALOG: 'BLE'
  stage: genLicense
  tags:
    - LINUX
  before_script:
  script:
    - date
    - generat_license_list
    - date
  artifacts:
    paths:
    - "license_list_gen.txt"
    - "no_license_list_gen.txt"
    - "mismatch_license_file_gen.txt"
  when: manual
  
checkLicense:
  variables:
    CODE_COMPILE_ARCH: 'TC32'
    COV_PF_CATALOG: 'BLE'
  stage: checkLicense
  tags:
    - LINUX
  allow_failure: yes
  before_script:
  script:
    - date
    - check_license
    #- generat_license_list # For no license files
    - date
  artifacts:
    when: always
    paths:
    - "mismatch_license.txt"
    - "no_license*.txt"
    - "unknow_type_file.txt"

build_sample:
  stage: build_sample
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x b80_ble_sdk/*.sh
    - date
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_ble_sample
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_ble_sample
    - date

build_module:
  stage: build_module
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x b80_ble_sdk/*.sh
    - date
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_module
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_module
    - date

build_master:
  stage: build_master
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x b80_ble_sdk/*.sh
    - date
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_master
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_master
    - date
    
build_feature:
  stage: build_feature
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x b80_ble_sdk/*.sh
    - date
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_ADVERTISING_IN_CONN_SLAVE_ROLE'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_SCANNING_IN_ADV_AND_CONN_SLAVE_ROLE'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_POWER_ADV'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_GATT_SECURITY'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_LL_DATA_LENGTH_EXTENSION_SLAVE'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_LL_DATA_LENGTH_EXTENSION_MASTER'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_BLE_PHY'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_MD_MASTER'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_MD_SLAVE'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_PHY_CONN'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_USER_BLT_SOFT_TIMER'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_USER_BLT_SOFT_UART'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - MACRO='FEATURE_TEST_MODE'
    - MACRO_VAL='TEST_FEATURE_BACKUP'
    - MACRO_PATH='./b80_ble_sdk/vendor/feature_test/feature_config.h'
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208_feature_test
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk/  -cleanBuild tc_ble_simple_sdk_8208/8208B_feature_test
    
    - date
  when: manual
    
clean_build:
  stage: clean_build
  tags:
    - LINUX
    - TC32
  script:
    - ls -a
    - rm -r * .git*
    - ls -a
  when: always
  
plainPW_check:
  stage: plainPW_check 
  tags:
    - LINUX
  script:
    - echo "Enter Plain Password checking stage"
    - check_plain_weak_password | tee result.txt
    - ls -l result.txt
    - echo "Error List:"
    - cat result.txt
  artifacts:
    paths:
    - result.txt
  when: manual

# The cov job definition
cov:
  variables:
    CODE_COMPILE_ARCH: 'TC32'
    COV_PF_CATALOG: 'BLE'
  stage: cov
  tags:
    - COV    
    - LINUX    
    - TC32
  before_script:
  script:
    - chmod +x b80_ble_sdk/*.sh
    - $COV_B COV_$CI_PROJECT_NAME $COV_B_TEMPLATE/$CODE_COMPILE_ARCH $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./b80_ble_sdk -cleanBuild b80_ble_sdk/8208_ble_sample
    - $COV_A COV_$CI_PROJECT_NAME 
    - cov_add_commit_steam_project_2_platform.sh
  when: manual

oss:
  tags:
    - OSS
  stage: oss
  script:
    - oss_checking .
  artifacts:
    when: always
    paths:
    - scan_result
  when: manual

fossid:
  tags:
    - FOSSID
  stage: fossid
  script:
    - fossid_check.sh
  artifacts:
    paths:
    - fossid*.txt
  when: manual

.release_sdk_template: &release_sdk_template
  variables:
    PACK_NAME: "release_sdk_template"
  stage: release_customize_sdk	
  tags:
    - windows_tc32_test
  script:
    - sdk_release_customize.sh ./release_sdk_config
  artifacts:
    name: "$PACK_NAME"
    expire_in: '3 yrs'
    paths:
    - "./b80_ble_sdk"
    - "./README.md"
    - "./doc"
  when: manual

release_sdk_P5_B80:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80_V3.4.2.0_P5"

release_sdk_P10_B80:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80_V3.4.2.0_P10"

release_sdk_P12_B80:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80_V3.4.2.0_P12"

release_sdk_custom_made_P0_B80:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80_V3.4.2.0_custom_made_P0"

release_sdk_custom_made_P5_B80:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80_V3.4.2.0_custom_made_P5"

release_sdk_custom_made_P10_B80:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80_V3.4.2.0_custom_made_P10"

release_sdk_custom_made_P12_B80:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80_V3.4.2.0_custom_made_P12"

release_sdk_P5_B80B:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80B_V3.4.2.0_P5"

release_sdk_P10_B80B:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80B_V3.4.2.0_P10"

release_sdk_P12_B80B:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80B_V3.4.2.0_P12"

release_sdk_custom_made_P0_B80B:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80B_V3.4.2.0_custom_made_P0"

release_sdk_custom_made_P5_B80B:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80B_V3.4.2.0_custom_made_P5"

release_sdk_custom_made_P10_B80B:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80B_V3.4.2.0_custom_made_P10"

release_sdk_custom_made_P12_B80B:
  <<: *release_sdk_template
  variables:
    PACK_NAME: "tc_ble_simple_sdk_B80B_V3.4.2.0_custom_made_P12"

